name: Compile Typst Document

on:
  push:
    branches:
      - main
    tags:
      - 'v*'  # This triggers the workflow on version tags

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Compile Typst document to PDF
        uses: lvignoli/typst-action@main
        with:
          source_file: *.typ  # Specify your Typst file here

      - name: Upload PDF to Releases
        uses: softprops/action-gh-release@v1
        with:
          files: *.pdf  # The output PDF file
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub token for authentication
